2025-06-27 16:45:19,834 - speechbrain.utils.quirks - INFO - Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
2025-06-27 16:45:19,835 - speechbrain.utils.quirks - INFO - Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
2025-06-27 16:45:19,835 - speechbrain.core - INFO - Beginning experiment!
2025-06-27 16:45:19,835 - speechbrain.core - INFO - Experiment folder: results/augment_noise_CRDNN/1986
2025-06-27 16:45:21,321 - speechbrain.utils.superpowers - DEBUG - apturl==0.5.2
asttokens==3.0.0
backcall==0.2.0
bcrypt==3.1.7
blinker==1.4
Brlapi==0.7.0
certifi==2019.11.28
cffi==1.17.1
chardet==3.0.4
Click==7.0
colorama==0.4.3
comm==0.2.2
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
debugpy==1.8.13
decorator==5.2.1
defer==1.0.6
distro==1.4.0
distro-info==0.23+ubuntu1.1
duplicity==0.8.12.0
entrypoints==0.3
executing==2.2.0
fasteners==0.14.1
filelock==3.16.1
fsspec==2025.3.0
future==0.18.2
httplib2==0.14.0
huggingface-hub==0.29.3
HyperPyYAML==1.2.2
idna==2.8
importlib-metadata==8.5.0
ipykernel==6.29.5
ipython==8.12.3
jedi==0.19.2
jinja2==3.1.6
joblib==1.4.2
jupyter-client==8.6.3
jupyter-core==5.7.2
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
monotonic==1.5
mpmath==1.3.0
nest-asyncio==1.6.0
netifaces==0.10.4
networkx==3.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.8.93
nvidia-nvtx-cu12==12.1.105
oauthlib==3.1.0
olefile==0.46
packaging==24.2
paramiko==2.6.0
parso==0.8.4
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
platformdirs==4.3.6
prompt-toolkit==3.0.50
protobuf==3.6.1
psutil==7.0.0
pure-eval==0.2.3
pycairo==1.16.2
pycparser==2.22
pycups==1.9.73
pygments==2.19.1
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyRFC3339==1.1
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.9.0.post0
python-debian==0.1.36+ubuntu1.1
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
pyzmq==26.3.0
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
ruamel.yaml==0.18.10
ruamel.yaml.clib==0.2.8
scipy==1.10.1
SecretStorage==2.3.1
sentencepiece==0.2.0
simplejson==3.16.0
six==1.14.0
soundfile==0.13.1
speechbrain==1.0.2
ssh-import-id==5.10
stack-data==0.6.3
sympy==1.13.3
systemd-python==234
torch==2.4.1
torchaudio==2.4.1
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
triton==3.0.0
typing-extensions==4.13.0
ubuntu-drivers-common==0.0.0
ubuntu-pro-client==8001
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
wadllib==1.3.3
wcwidth==0.2.13
xkit==0.0.0
zipp==3.20.2


2025-06-27 16:45:21,347 - speechbrain.utils.superpowers - DEBUG - e97d5cc


2025-06-27 16:45:21,549 - speechbrain.utils.checkpoints - DEBUG - Registered checkpoint save hook for save
2025-06-27 16:45:21,549 - speechbrain.utils.checkpoints - DEBUG - Registered checkpoint load hook for load_if_possible
2025-06-27 16:45:21,551 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2025-06-27 16:47:14,248 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 267, in load_or_create
    if not self.load_if_possible(path):
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 665, in load_if_possible
    self.load(path)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 625, in load
    self._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1189, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1047, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 764, in _set_extras
    self.starting_index = extras["starting_index"]
KeyError: 'starting_index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cestien/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/cestien/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/cestien/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/cestien/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/cestien/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/cestien/.vscode/extensions/ms-python.debugpy-2025.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/home/cestien/trabajo/zero-res/zrc/tutorial_notebooks/pytorch/timit/train.py", line 243, in <module>
    train_data, valid_data, test_data, label_encoder = dataio_prep(hparams)
  File "/home/cestien/trabajo/zero-res/zrc/tutorial_notebooks/pytorch/timit/train.py", line 192, in dataio_prep
    label_encoder.load_or_create(
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 283, in load_or_create
    self.load(path)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 625, in load
    self._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1189, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1047, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 764, in _set_extras
    self.starting_index = extras["starting_index"]
KeyError: 'starting_index'
2025-06-27 16:49:13,520 - speechbrain.utils.quirks - INFO - Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
2025-06-27 16:49:13,520 - speechbrain.utils.quirks - INFO - Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
2025-06-27 16:49:13,520 - speechbrain.core - INFO - Beginning experiment!
2025-06-27 16:49:13,520 - speechbrain.core - INFO - Experiment folder: results/augment_noise_CRDNN/1986
2025-06-27 16:49:14,530 - speechbrain.utils.superpowers - DEBUG - apturl==0.5.2
asttokens==3.0.0
backcall==0.2.0
bcrypt==3.1.7
blinker==1.4
Brlapi==0.7.0
certifi==2019.11.28
cffi==1.17.1
chardet==3.0.4
Click==7.0
colorama==0.4.3
comm==0.2.2
command-not-found==0.3
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
debugpy==1.8.13
decorator==5.2.1
defer==1.0.6
distro==1.4.0
distro-info==0.23+ubuntu1.1
duplicity==0.8.12.0
entrypoints==0.3
executing==2.2.0
fasteners==0.14.1
filelock==3.16.1
fsspec==2025.3.0
future==0.18.2
httplib2==0.14.0
huggingface-hub==0.29.3
HyperPyYAML==1.2.2
idna==2.8
importlib-metadata==8.5.0
ipykernel==6.29.5
ipython==8.12.3
jedi==0.19.2
jinja2==3.1.6
joblib==1.4.2
jupyter-client==8.6.3
jupyter-core==5.7.2
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==2.1.5
matplotlib-inline==0.1.7
monotonic==1.5
mpmath==1.3.0
nest-asyncio==1.6.0
netifaces==0.10.4
networkx==3.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.8.93
nvidia-nvtx-cu12==12.1.105
oauthlib==3.1.0
olefile==0.46
packaging==24.2
paramiko==2.6.0
parso==0.8.4
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
platformdirs==4.3.6
prompt-toolkit==3.0.50
protobuf==3.6.1
psutil==7.0.0
pure-eval==0.2.3
pycairo==1.16.2
pycparser==2.22
pycups==1.9.73
pygments==2.19.1
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyRFC3339==1.1
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.9.0.post0
python-debian==0.1.36+ubuntu1.1
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
pyzmq==26.3.0
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
ruamel.yaml==0.18.10
ruamel.yaml.clib==0.2.8
scipy==1.10.1
SecretStorage==2.3.1
sentencepiece==0.2.0
simplejson==3.16.0
six==1.14.0
soundfile==0.13.1
speechbrain==1.0.2
ssh-import-id==5.10
stack-data==0.6.3
sympy==1.13.3
systemd-python==234
torch==2.4.1
torchaudio==2.4.1
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
triton==3.0.0
typing-extensions==4.13.0
ubuntu-drivers-common==0.0.0
ubuntu-pro-client==8001
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
wadllib==1.3.3
wcwidth==0.2.13
xkit==0.0.0
zipp==3.20.2


2025-06-27 16:49:14,559 - speechbrain.utils.superpowers - DEBUG - e97d5cc


2025-06-27 16:49:14,608 - speechbrain.utils.checkpoints - DEBUG - Registered checkpoint save hook for save
2025-06-27 16:49:14,608 - speechbrain.utils.checkpoints - DEBUG - Registered checkpoint load hook for load_if_possible
2025-06-27 16:49:14,609 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2025-06-27 16:49:14,610 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 267, in load_or_create
    if not self.load_if_possible(path):
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 665, in load_if_possible
    self.load(path)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 625, in load
    self._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1189, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1047, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 764, in _set_extras
    self.starting_index = extras["starting_index"]
KeyError: 'starting_index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 243, in <module>
    train_data, valid_data, test_data, label_encoder = dataio_prep(hparams)
  File "train.py", line 192, in dataio_prep
    label_encoder.load_or_create(
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 283, in load_or_create
    self.load(path)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 625, in load
    self._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1189, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 1047, in _set_extras
    super()._set_extras(extras)
  File "/home/cestien/.local/lib/python3.8/site-packages/speechbrain/dataio/encoder.py", line 764, in _set_extras
    self.starting_index = extras["starting_index"]
KeyError: 'starting_index'
